MissionSite/Controllers/HomeController.cs

/*
 * This is Project 2
 * A Mission Site to have some information and questions
 * 
 * created by group 12 of section 2
 * 
 * Brett Adamson
 * Kory Hutchison
 * Nathan Marrs
 * Alex Pratt
 *
 * 
 * */


using MissionSite.DAL;
using MissionSite.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace MissionSite.Controllers
{
    public class HomeController : Controller
    {
        private MissionFAQsContext db = new MissionFAQsContext();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            return View();
        }

        //This is the Contact method that has the list of options for the dropdown list.
        public ActionResult Contact()
        {
            List<SelectListItem> subject_options = new List<SelectListItem>();
            subject_options.Add(new SelectListItem { Text = "Choose One", Selected = true });
            subject_options.Add(new SelectListItem { Text = "Mission Question", Value = "0" });
            subject_options.Add(new SelectListItem { Text = "Website Problem", Value = "1" });
            subject_options.Add(new SelectListItem { Text = "Other", Value = "2"});
            ViewBag.SubjectOptions = subject_options;

            return View();
        }

        public ActionResult Login()
        {
            return View();
        }

        //verify their login, and send them to the screen if they are in our database. if not, show an error message
        [HttpPost]
        public ActionResult Login(FormCollection form, bool rememberMe = false)
        {
            IEnumerable<Users> find_user = db.Database.SqlQuery<Users>("select * from Users where UserEmail = '" + form["Email"].ToString() + "';");

            try
            {
                Users current_user = db.User.Find(find_user.First().UserID);

                if (current_user != null)
                {
                    if (current_user.UserPassword.Equals(form["Password"].ToString()))
                    {
                        FormsAuthentication.SetAuthCookie(current_user.UserEmail, rememberMe);
                        return RedirectToAction("Index", "Home");
                    }
                    else
                    {
                        ViewBag.ErrorMessage = "Invalid Email / Password.";
                    }
                }
            }
            catch
            {
                ViewBag.ErrorMessage = "Invalid Email / Password.";
            }

            return View();
        }
    }
}

MissionSite/Controllers/MissionController.cs
using MissionSite.DAL;
using MissionSite.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MissionSite.Controllers
{
    public class MissionController : Controller
    {
        private MissionFAQsContext db = new MissionFAQsContext();
        // GET: Mission
        public ActionResult Index(string mission)
        {
            IEnumerable<Missions> MissionInfo;
            switch (mission)
            {
                case "Colombia Bogota North":
                    MissionInfo = db.Database.SqlQuery<Missions>("Select * From Missions Where MissionName = 'Colombia Bogota North'");
                    break;
                case "Brasil Belem":
                    MissionInfo = db.Database.SqlQuery<Missions>("Select * From Missions Where MissionName = 'Brasil Belem'");
                    break;
                default: // "Brasil Curitiba":
                    MissionInfo = db.Database.SqlQuery<Missions>("Select * From Missions Where MissionName = 'Brasil Curitiba'");
                    break;
            }

            return View(MissionInfo);
        }

    }
}

MissionSite/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MissionSite.DAL;
using MissionSite.Models;
using System.Web.Security;

namespace MissionSite.Controllers
{
    public class UsersController : Controller
    {
        private MissionFAQsContext db = new MissionFAQsContext();

        // GET: Users
        public ActionResult Index()
        {
            return View(db.User.ToList());
        }

        // GET: Users/Details/5
        public ActionResult Details(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Users users = db.User.Find(id);
            if (users == null)
            {
                return HttpNotFound();
            }
            return View(users);
        }

        // GET: Users/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UserID,UserEmail,UserPassword,UserFirstName,UserLastName")] Users users, bool rememberMe = false)
        {
            if (ModelState.IsValid)
            {
                db.User.Add(users);
                db.SaveChanges();
                FormsAuthentication.SetAuthCookie(users.UserEmail, rememberMe);
                ViewBag.UserID = users.UserID;
                return RedirectToAction("Index", "Home");
            }

            return View(users);
        }

        // GET: Users/Edit/5
        public ActionResult Edit(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Users users = db.User.Find(id);
            if (users == null)
            {
                return HttpNotFound();
            }
            return View(users);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UserID,UserEmail,UserPassword,UserFirstName,UserLastName")] Users users)
        {
            if (ModelState.IsValid)
            {
                db.Entry(users).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(users);
        }

        // GET: Users/Delete/5
        public ActionResult Delete(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Users users = db.User.Find(id);
            if (users == null)
            {
                return HttpNotFound();
            }
            return View(users);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(decimal id)
        {
            Users users = db.User.Find(id);
            db.User.Remove(users);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MissionSite/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<ol class="breadcrumb">
    <li>@Html.ActionLink("Home", "Index", "Home")</li>
    <li class="active">About</li>
</ol>
<body style="margin: 0">
    <div class="jumbotron" style="margin-bottom: 0">
        <div class="container-fluid">
            <h1>About</h1>
            <p class="lead">What we're all about.</p>
        </div>
    </div>
    <div class="container">
        <div class="col-md-6">
            <img class="img-responsive" src="~/Content/Images/info.jpg" />
        </div>
        <div class="col-md-6" style="padding-top: 15%">
            <h1>What We Do</h1>
            <h3>
                We are here to help future missionaries find the best information about their missions. We go out there
                and find all the facts for you so you don't have to. We do this so everyone can have a basic idea of what their
                mission is going to be like.
            </h3>
        </div>
    </div>
    <div class="container">
    <div class="col-md-6" style="padding-top: 15%">
        <h1>This is what it's all about</h1>
        <h3>
            Missions are the best! Even though each mission has a different mission president and different climate, 
            it's all about serving the Lord! And we want to see the users of this site sharing their experiences with
            everyone else. That way, we can get everyone excited about serving a mission!
        </h3>
    </div>
    <div class="col-md-6">
        <img class="img-responsive" src="~/Content/Images/kory.jpg" />
    </div>
    </div>

</body>

MissionSite/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<ol class="breadcrumb">
    <li>@Html.ActionLink("Home", "Index", "Home", null, null)</li>
    <li class="active">Contact</li>
</ol>

<div class="jumbotron">
    <div class="container">
        <h1>Have a Question?</h1>
        <p class="lead">Feel free to contact us!</p>
    </div>
</div>


<div class="container-fluid">
    <div class="col-md-4">
        @using (Html.BeginForm("Contact", "Home", FormMethod.Post, new { @class = "form-group" }))
        {
            <div class="row">
                <div class="col-md-12">
                    <h3>Name</h3>
                    @Html.TextBox("Name", "", new { @class = "form-control" })
                    <h3>Email</h3>
                    @Html.TextBox("Email", "", new { @class = "form-control" })
                    <h3>Subject</h3>
                    @Html.DropDownList("SubjectOptions", null, new { @class = "form-control" })
                </div>
                <div class="clearfix"></div>
                <div class="col-md-12">
                    <h3>Message</h3>
                    @Html.TextArea("Message", "", new { @class = "form-control text_message", rows = "6" })
                </div>
            </div>
            <br />
            <p>
                <input type="submit" value="Submit" class="btn btn-primary btn-lg" />
            </p>
        }
    </div>
    <div class="col-md-8" style="text-align: center">
        <iframe width="80%" height="400" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https:///www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3045.075945108425!2d-111.65150428502238!3d40.251843479384576!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x874d90bc4aa0b68d%3A0xbf3eb3a3f30fdc4c!2sBrigham+Young+University!5e0!3m2!1sen!2sus!4v1477621290000" id="map_format"></iframe>
        <br />
        <br />
        <div class="well" style="width: 50%; display: block; margin: auto">
            <p>Email: contact@missionfacts.com</p>
            <p>Phone: (801) 555-5555</p>
        </div>
    </div>
</div>

<div class="container-fluid"></div>
 

MissionSite/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<body id="LandingPage">

    <div id="LandJumbo" class="jumbotron">
        <h1>Prepare to Serve</h1>
        <p class="lead">Need the facts? Take a look at what return missionaries have said about your mission. </p>
        <p>@Html.ActionLink("View My Mission", "Index", "Mission", null, new { @class="btn btn-primary btn-lg "}) </p>
    </div>

</body>



MissionSite/Views/Home/Login.cshtml
@{
    ViewBag.Title = "Login";
}

<h2 class="text-center">Login</h2>

@using (Html.BeginForm("Login", "Home", FormMethod.Post, new { @class = "form-signin" }))
{
    <h4 class="form-signin-heading">Please enter your login information</h4>
    <label for="inputUsername" class="sr-only">Username</label>
    @Html.TextBox("Email", "", new { type = "text", id = "inputEmail", @class = "form-control", placeholder = "Email", required = true, autofocus = true })
    <label for="inputPassword" class="sr-only">Password</label>
    @Html.Password("Password", "", new { type = "password", id = "inputPassword", @class = "form-control", placeholder = "Password", required = true })
    <button class="btn btn-lg btn-primary" type="submit">Sign in</button> <span></span> @Html.ActionLink("Register", "Create", "Users", "", new { @class = "btn btn-lg btn-success" })
}

@if (ViewBag.ErrorMessage != null)
{
    <div class="row">
        <div class="col-sm-4">
        </div>
        <div class="col-sm-4">
            <div class="alert alert-danger">
                @ViewBag.ErrorMessage
            </div>
        </div>
        <div class="col-sm-4">
        </div>
    </div>
}


